version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "JFinchy"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    
  # Security updates only for critical/high severity
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    target-branch: "main"
    labels:
      - "security"
      - "critical"
    commit-message:
      prefix: "security(deps)"
    # Only security updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"