#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Source nvm and use correct Node version
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -f .nvmrc ] && nvm use

bunx lint-staged
