name: Security Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install
      
    - name: Run security audit
      run: |
        # Create package-lock.json for npm audit
        npm i --package-lock-only
        npm audit --audit-level moderate
        
    - name: Type check
      run: bun run type-check
      
    - name: Lint check
      run: bun run lint:check
      
    - name: Security health check
      run: bun run test src/tests/unit/security-health.test.ts
      if: false # Enable when test exists